refactor: Remove mappings for frontend registration URLs
virtualidentityag/diakonie-onlineBeratung-backend pull request #1
Opened 2021-04-01 15:31 UTC by amannn

TODO: Figure out if the proxy passes through all unknown calls.

2021-04-13 07:10 UTC, koepferd requested changes

2021-04-13 07:10 UTC, koepferd commented on nginx/conf/locations/addiction.conf
>  location = /03pages.01registrationFormular.html {
As this page has been deprecated for a while and is not used anymore, please also remove the redirect.

2021-04-13 09:25 UTC, amannn commented on nginx/conf/locations/addiction.conf
>  location = /03pages.01registrationFormular.html {
Done!

2021-04-28 08:48 UTC, koepferd approved these changes

2021-04-28 11:54 UTC, merged